name: Ruff Formatter

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install ruff

      - name: Run Ruff formatter
        run: ruff format *.py

      - name: Commit changes 
        uses: stefanzweifel/git-auto-commit-action@v5
        
