name: Ruff Formatter

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install ruff

      - name: Run Ruff formatter
        run: ruff format *.py

      - name: Commit changes
        run: |
          git config --global user.email "armansinghgrewal@gmail.com"
          git config --global user.name "ArmanGrewal007"
          git commit -am "Apply Ruff formatting" --allow-empty
      - name: Debugging Output
        run: |
          echo "Current directory: $(pwd)"
          echo "List files: $(ls -al)"
      - name: Push changes
        # uses: ad-m/github-push-action@master
        # uses: mikeal/publish-to-github-action@master
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
